openapi: 3.0.0
info:
  title: Health Endpoint
  version: 1.0.0
  description: Checks the health and availability of the API service.
paths:
  /health:
    get:
      summary: Check API health
      responses:
        '200':
          description: API is healthy.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
        '500':
          description: API is unhealthy.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: unhealthy
